name: Build docker image and push

on: push

jobs:
  build-and-push-zapper-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Build the tagged Docker image
        run: docker build --file Zapper/zapper-backend/Dockerfile --tag sabyrzhan/angular-projects:zapper-backend-latest .
      - name: Push the tagged Docker image
        run: docker push sabyrzhan/angular-projects:zapper-backend-latest .
