name: "Zapper-backend: build docker image and push to GitHub"

on: push

defaults:
  run:
    working-directory: Zapper/zapper-backend

jobs:
  build-and-push-zapper-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build the tagged Docker image
        run: docker build --file Dockerfile --tag sabyrzhan/angular-projects:zapper-backend-latest .
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          push: true
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: sabyrzhan/angular-projects:zapper-backend-latest
          tag_with_ref: false
          tags: zapper-backend-latest
