name: "Zapper-backend: build docker image and push to GitHub"

on: push

defaults:
  run:
    working-directory: Zapper/zapper-backend

jobs:
  build-and-push-zapper-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build the tagged Docker image
        run: docker build --file Dockerfile --tag sabyrzhan/angular-projects:zapper-backend-latest .
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push to GitHub Packages
        run: docker push sabyrzhan/angular-projects:zapper-backend-latest
